# Generated by Django 5.0.7 on 2024-08-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('tester', 'Tester'), ('hr', 'HR'), ('project_manager', 'Project Manager'), ('teamlead_dev', 'Team Lead (Dev)'), ('teamlead_qa', 'Team Lead (QA)'), ('ceo', 'CEO'), ('accountant', 'Accountant')], default='developer', max_length=50),
        ),
    ]
